config/routes.rb
Rails.application.routes.draw do
  get 'show/edit'
  get 'show/new'
  get 'users/top'
  get 'users/show'
  get 'users/edit'
  get 'books/new'
  get 'books/index'
  get 'books/show'
  get 'books/edit'
  devise_for :users
root to: "homes#top"
 get 'homes/about', to: 'homes#about', as: :about
resources :books, only: [:new, :create, :index, :show, :destroy]
  resources :users, only: [:show, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   has_one_attached :image
   belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_images, dependent: :destroy


  has_one_attached :profile_image

  has_many :post_images, dependent: :destroy

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end


  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def destroy
    book = 削除するBookレコードを取得
    book.削除
    redirect_to Bookの一覧ページへのパス
  end


  def index
  end

  def show
  end

  def edit
  end

  private

  def book_params
    params.require(:article).permit(:title, :content)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about

  end

end

app/controllers/show_controller.rb
class ShowController < ApplicationController
  def edit
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user =　User.find(params[:id])
    @books = @user.book
  end

  def edit
  end

  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<% @book.each do |post_image| %>
  <div>
    <%= link_to book_path(book.id) do %>
      <%= image_tag book.get_image %>
    <% end %>

    <p>投稿ユーザー画像：<%= image_tag book.user.get_profile_image(100,100) %></p>
    <p>ショップ名：<%= book.shop_name %></p>
    <p>説明：<%= book.caption %></p>
    <p>ユーザーネーム：<%= book.user.name %></p>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>新規投稿</h1>

<%= form_with model: @book, url:'/books' do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>
  <!-- 追加部分 -->
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <%= f.submit '投稿' %>

<% end %>

app/views/books/show.html.erb
<div>
  <%= image_tag @book.get_image %>
  <p>ショップ名：<%= @book.shop_name %></p>
  <p>説明：<%= @book.caption %></p>
  <p>投稿ユーザー画像：<%= image_tag @book.user.get_profile_image(100,100) %></p>  <p>ユーザーネーム：<%= @book.user.name %></p>
  <p>投稿日時：<%= @book.created_at.strftime('%Y/%m/%d') %></p>
  <% if @book.user == current_user %>
    <%= link_to "削除", book_path(@book), method: :delete %>
  <% end %>
</div>

app/views/homes/about.html.erb
<h1>Aboutページ</h1>
<p><%= @message %></p>

app/views/homes/top.html.erb
<h1>Topページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <body>
    <header>
    <% if user_signed_in? %>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
  </header>
    <%= yield %>
  </body>

  <script src="https://kit.fontawesome.com/6b34ffe20c.js" crossorigin="anonymous"></script>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

     <footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

</html>

app/views/show/edit.html.erb
<h1>Show#edit</h1>
<p>Find me in app/views/show/edit.html.erb</p>

app/views/show/new.html.erb
<h1>Show#new</h1>
<p>Find me in app/views/show/new.html.erb</p>